# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    sync_code_signing(type: "appstore")
    build_app(workspace: "Hereminders.xcworkspace", scheme: "Hereminders")
    upload_to_testflight
  end

  lane :certificates do
    match(app_identifier: ["com.going.Hereminders", "com.going.Hereminders.HeremindersTodayExtension", "com.going.Hereminders.watchkitapp", "com.going.Hereminders.watchkitapp.watchkitextension"], type: "development")
    match(app_identifier: ["com.going.Hereminders", "com.going.Hereminders.HeremindersTodayExtension", "com.going.Hereminders.watchkitapp", "com.going.Hereminders.watchkitapp.watchkitextension"], type: "appstore")
  end
end
